### ISSUE TITLE
G3.152 Create phenotypes backup page

### ISSUE THREAD

**Issue by reynoldtan** [TripalCultivate/TripalCultivate-Phenotypes#152]
### Branch

g3.153-BackupPage

### Groups

Group 3 - Search | Browse | Tools

### Describe

Setup a Drupal configuration entity to allow user to backup phenotypes data collection file. The idea is that each entity/page/instance is a single backup. By using the configuration entity API we get a lot of features for free. See [Drupal Creating a configuration entity type](https://www.drupal.org/docs/drupal-apis/configuration-api/creating-a-configuration-entity-type). **Note: There is a drush generate command to create these files for you -do not do it manually.**

### Design

Entity Type name: Phenotypic Data Backup (phenodata_backup)

Interface:
1. A basic form interface that with the following fields:

- A data file to backup. This will be a drupal file field.
- Project - to specify to which project the data file relates to. This will be an entity relationship field that references Research Experiment Tripal Content Types.
- Comment - user notes and comments. This will be a Drupal Long Text Area.

![Image](https://github.com/user-attachments/assets/49c81be0-e402-41bb-b89e-f0e2fef3933e)

2. Save the file in: `public://phenotype-backups` and rename based on projectid and date.
3. Create a view listing of the files. Sorted by date + project name (Allow filter for project name) The project filter will use the entity relationship handler which I hope supports select out of the box 🙏 

![Image](https://github.com/user-attachments/assets/5cd47a12-c1c7-4958-8a79-36e4d6283c81)

Backend:
```
Configuration entity schema:
trpcultivate_phenotypes.data_file_backup:
  type: config_entity
  label: 'Data Collection File Backup'
  mapping:
    file_id
      type: string
      label: 'File object'
    backup_date:
      type: date
      label: 'Date file was uploaded'
    project_id:
      type: int
      label: 'The project id of the project the data file is specific to'
    comments:
      type: text
      label: 'Notes or comments about the file'
   user_id:
      type: int
      label: 'The user id number'
   ```

### NOTES:

1. Discuss how to reference validation result performed to the file. Perhaps we add a field to the config entity that contains the validation results? This may need to be a custom Drupal field 🤔 Let's worry about this once we get the rest setup.
2. Location to save all backed up files. Currently we have it as `public://phenotype-backups` but we may want to take a small amount of time to see how hard it is to make these private?
3. Given recent difficulty in setting up a filter in view using select box, what should the filter field be? Hopefully using an entity reference will provide a better select filter without needing hard-coding.
